# Generated by Django 5.2.1 on 2025-05-21 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('tasks', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_schedules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='friday_schedule', to='scheduleModule.dailyschedule')),
                ('monday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monday_schedule', to='scheduleModule.dailyschedule')),
                ('saturday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saturday_schedule', to='scheduleModule.dailyschedule')),
                ('sunday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sunday_schedule', to='scheduleModule.dailyschedule')),
                ('thursday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thursday_schedule', to='scheduleModule.dailyschedule')),
                ('tuesday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tuesday_schedule', to='scheduleModule.dailyschedule')),
                ('wednesday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wednesday_schedule', to='scheduleModule.dailyschedule')),
            ],
        ),
    ]
