# Generated by Django 5.2.1 on 2025-05-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleModule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyschedule',
            name='week_end_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='week_start_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
