# Generated by Django 5.2.1 on 2025-05-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleModule', '0002_weeklyschedule_week_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyschedule',
            name='week_end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyschedule',
            name='week_start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
