# Generated by Django 5.2.1 on 2025-05-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleModule', '0003_alter_weeklyschedule_week_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyschedule',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='dailyschedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='dailyschedule',
            name='start_time',
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='Date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='WeeklySchedule',
        ),
    ]
