# Generated by Django 5.2.1 on 2025-05-21 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleModule', '0004_remove_dailyschedule_day_of_week_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyschedule',
            name='tasks',
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='scheduleModule.dailyschedule')),
            ],
        ),
    ]
